package hydro.bolt.tokens;

public enum TokenType {
    IDENTIFIER,
    KEYWORD,

    INTEGER_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    STRING_LITERAL,

    PLUS, MINUS, STAR, SLASH, PERCENT,
    INCREMENT, DECREMENT,

    ASSIGN,
    PLUS_ASSIGN, MINUS_ASSIGN, STAR_ASSIGN, SLASH_ASSIGN, PERCENT_ASSIGN,
    BIT_AND_ASSIGN, BIT_OR_ASSIGN, BIT_XOR_ASSIGN,
    SHIFT_LEFT_ASSIGN, SHIFT_RIGHT_ASSIGN,

    EQUAL, NOT_EQUAL,
    LESS, LESS_EQUAL,
    GREATER, GREATER_EQUAL,

    LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,

    BIT_AND, BIT_OR, BIT_XOR, BIT_NOT,
    SHIFT_LEFT, SHIFT_RIGHT,

    ARROW,
    DOT,

    LPAREN, RPAREN,
    LBRACE, RBRACE,
    LBRACKET, RBRACKET,

    COMMA,
    SEMICOLON,
    COLON,
    QUESTION,

    AT,

    EOF
}
